import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import Nav from './components/navbar';
import Footer from './components/footer';

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer/> 

          <Providers>
            <Nav/>
            {children}
            <Footer/>
          </Providers>
      </body>
    </html>
  )
}
